# Generated by Django 4.2.5 on 2023-09-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
