# Generated by Django 4.2.6 on 2023-10-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProducto', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
