# Generated by Django 4.2.6 on 2024-07-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProducto', '0005_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProducto.producto'),
        ),
    ]
